input_labels:
  - "Roku Ultra"
  - "Roku 3"
  - "Apple TV"
  - "Chromecast"
  - "Fire TV"
  - "None"
  - "None"
  - "None"

output_video_labels:
  - "Living Room"
  - "Bar"
  - "Master Bed"
  - "Master Bath"
  - "Guest"
  - "Office"
  - "Rec Room"
  - "Gym"

output_audio_labels:
  - "Living Room"
  - "Bar"
  - "Master Bed"
  - "Master Bath"
  - "Guest"
  - "Office"
  - "DeckUp"
  - "Deck Down"
